# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 580)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/build-Rahbin_GUI_v2-Desktop_Qt_5_7_0_GCC_64bit-Debug/rahbin.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.setup_tab = QtWidgets.QWidget()
        self.setup_tab.setObjectName("setup_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.setup_tab)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        self.install_btn = QtWidgets.QPushButton(self.setup_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.install_btn.setFont(font)
        self.install_btn.setObjectName("install_btn")
        self.verticalLayout.addWidget(self.install_btn)
        self.run_btn = QtWidgets.QPushButton(self.setup_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.verticalLayout.addWidget(self.run_btn)
        self.stop_btn = QtWidgets.QPushButton(self.setup_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.stop_btn.setFont(font)
        self.stop_btn.setObjectName("stop_btn")
        self.verticalLayout.addWidget(self.stop_btn)
        self.reboot_btn = QtWidgets.QPushButton(self.setup_tab)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.reboot_btn.setFont(font)
        self.reboot_btn.setObjectName("reboot_btn")
        self.verticalLayout.addWidget(self.reboot_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_6.setContentsMargins(-1, -1, -1, 10)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(self.setup_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.show_ttc_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.show_ttc_chb.setFont(font)
        self.show_ttc_chb.setObjectName("show_ttc_chb")
        self.gridLayout_2.addWidget(self.show_ttc_chb, 6, 0, 1, 1)
        self.save_ldw_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save_ldw_chb.setFont(font)
        self.save_ldw_chb.setObjectName("save_ldw_chb")
        self.gridLayout_2.addWidget(self.save_ldw_chb, 2, 1, 1, 1)
        self.tracker_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tracker_chb.setFont(font)
        self.tracker_chb.setObjectName("tracker_chb")
        self.gridLayout_2.addWidget(self.tracker_chb, 3, 1, 1, 1)
        self.save_fcw_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save_fcw_chb.setFont(font)
        self.save_fcw_chb.setChecked(True)
        self.save_fcw_chb.setObjectName("save_fcw_chb")
        self.gridLayout_2.addWidget(self.save_fcw_chb, 2, 0, 1, 1)
        self.display_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.display_chb.setFont(font)
        self.display_chb.setObjectName("display_chb")
        self.gridLayout_2.addWidget(self.display_chb, 7, 0, 1, 1)
        self.roi_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.roi_chb.setFont(font)
        self.roi_chb.setObjectName("roi_chb")
        self.gridLayout_2.addWidget(self.roi_chb, 5, 0, 1, 1)
        self.alaram_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.alaram_chb.setFont(font)
        self.alaram_chb.setChecked(True)
        self.alaram_chb.setObjectName("alaram_chb")
        self.gridLayout_2.addWidget(self.alaram_chb, 3, 0, 1, 1)
        self.FCW_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.FCW_chb.setFont(font)
        self.FCW_chb.setChecked(True)
        self.FCW_chb.setObjectName("FCW_chb")
        self.gridLayout_2.addWidget(self.FCW_chb, 0, 0, 1, 1)
        self.ldw_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.ldw_chb.setFont(font)
        self.ldw_chb.setObjectName("ldw_chb")
        self.gridLayout_2.addWidget(self.ldw_chb, 0, 1, 1, 1)
        self.save_in_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save_in_chb.setFont(font)
        self.save_in_chb.setChecked(True)
        self.save_in_chb.setObjectName("save_in_chb")
        self.gridLayout_2.addWidget(self.save_in_chb, 1, 0, 1, 1)
        self.save_out_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.save_out_chb.setFont(font)
        self.save_out_chb.setObjectName("save_out_chb")
        self.gridLayout_2.addWidget(self.save_out_chb, 1, 1, 1, 1)
        self.show_detect_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.show_detect_chb.setFont(font)
        self.show_detect_chb.setObjectName("show_detect_chb")
        self.gridLayout_2.addWidget(self.show_detect_chb, 5, 1, 1, 1)
        self.show_dist_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.show_dist_chb.setFont(font)
        self.show_dist_chb.setObjectName("show_dist_chb")
        self.gridLayout_2.addWidget(self.show_dist_chb, 6, 1, 1, 1)
        self.regressor_chb = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.regressor_chb.setFont(font)
        self.regressor_chb.setObjectName("regressor_chb")
        self.gridLayout_2.addWidget(self.regressor_chb, 7, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 2, 1, 1, 1)
        self.username_text = QtWidgets.QLineEdit(self.setup_tab)
        self.username_text.setObjectName("username_text")
        self.gridLayout_6.addWidget(self.username_text, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.setup_tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.user_IP_text = QtWidgets.QLineEdit(self.setup_tab)
        self.user_IP_text.setObjectName("user_IP_text")
        self.gridLayout_6.addWidget(self.user_IP_text, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.setup_tab)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.setup_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 3, 1, 1, 1)
        self.calib4p_btn = QtWidgets.QPushButton(self.setup_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib4p_btn.sizePolicy().hasHeightForWidth())
        self.calib4p_btn.setSizePolicy(sizePolicy)
        self.calib4p_btn.setObjectName("calib4p_btn")
        self.gridLayout_6.addWidget(self.calib4p_btn, 5, 1, 1, 1)
        self.calibHorizon_btn = QtWidgets.QPushButton(self.setup_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibHorizon_btn.sizePolicy().hasHeightForWidth())
        self.calibHorizon_btn.setSizePolicy(sizePolicy)
        self.calibHorizon_btn.setObjectName("calibHorizon_btn")
        self.gridLayout_6.addWidget(self.calibHorizon_btn, 6, 1, 1, 1)
        self.calib_4p_ok_btn = QtWidgets.QPushButton(self.setup_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_4p_ok_btn.sizePolicy().hasHeightForWidth())
        self.calib_4p_ok_btn.setSizePolicy(sizePolicy)
        self.calib_4p_ok_btn.setObjectName("calib_4p_ok_btn")
        self.gridLayout_6.addWidget(self.calib_4p_ok_btn, 5, 0, 1, 1)
        self.calib_horizon_ok_btn = QtWidgets.QPushButton(self.setup_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calib_horizon_ok_btn.sizePolicy().hasHeightForWidth())
        self.calib_horizon_ok_btn.setSizePolicy(sizePolicy)
        self.calib_horizon_ok_btn.setObjectName("calib_horizon_ok_btn")
        self.gridLayout_6.addWidget(self.calib_horizon_ok_btn, 6, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_7)
        self.tabWidget.addTab(self.setup_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.status = QtWidgets.QLabel(self.centralWidget)
        self.status.setObjectName("status")
        self.gridLayout.addWidget(self.status, 2, 0, 1, 1)
        self.stream_tab = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stream_tab.sizePolicy().hasHeightForWidth())
        self.stream_tab.setSizePolicy(sizePolicy)
        self.stream_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.stream_tab.setObjectName("stream_tab")
        self.stream = QtWidgets.QWidget()
        self.stream.setObjectName("stream")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.stream)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stream_label = QtWidgets.QLabel(self.stream)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stream_label.sizePolicy().hasHeightForWidth())
        self.stream_label.setSizePolicy(sizePolicy)
        self.stream_label.setText("")
        self.stream_label.setTextFormat(QtCore.Qt.PlainText)
        self.stream_label.setAlignment(QtCore.Qt.AlignCenter)
        self.stream_label.setWordWrap(False)
        self.stream_label.setObjectName("stream_label")
        self.horizontalLayout.addWidget(self.stream_label)
        self.stream_tab.addTab(self.stream, "")
        self.gridLayout.addWidget(self.stream_tab, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stream_tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rahbin"))
        self.install_btn.setText(_translate("MainWindow", "Install"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.reboot_btn.setText(_translate("MainWindow", "reboot"))
        self.groupBox.setTitle(_translate("MainWindow", "Installation options"))
        self.show_ttc_chb.setText(_translate("MainWindow", "Show TTC"))
        self.save_ldw_chb.setText(_translate("MainWindow", "Save LDW"))
        self.tracker_chb.setText(_translate("MainWindow", "Tracker"))
        self.save_fcw_chb.setText(_translate("MainWindow", "Save FCW"))
        self.display_chb.setText(_translate("MainWindow", "Display on"))
        self.roi_chb.setText(_translate("MainWindow", "Show ROI"))
        self.alaram_chb.setText(_translate("MainWindow", "Alaram"))
        self.FCW_chb.setText(_translate("MainWindow", "FCW"))
        self.ldw_chb.setText(_translate("MainWindow", "LDW"))
        self.save_in_chb.setText(_translate("MainWindow", "Save Input"))
        self.save_out_chb.setText(_translate("MainWindow", "Save Output"))
        self.show_detect_chb.setText(_translate("MainWindow", "Show Detectoins"))
        self.show_dist_chb.setText(_translate("MainWindow", "Show dist"))
        self.regressor_chb.setText(_translate("MainWindow", "Regressor"))
        self.username_text.setText(_translate("MainWindow", "pi"))
        self.label_2.setText(_translate("MainWindow", "User"))
        self.user_IP_text.setText(_translate("MainWindow", "10.42.0"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_3.setText(_translate("MainWindow", "Calibration"))
        self.calib4p_btn.setText(_translate("MainWindow", "4 Points"))
        self.calibHorizon_btn.setText(_translate("MainWindow", "Horizon"))
        self.calib_4p_ok_btn.setText(_translate("MainWindow", "OK"))
        self.calib_horizon_ok_btn.setText(_translate("MainWindow", "OK"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setup_tab), _translate("MainWindow", "Setup"))
        self.status.setText(_translate("MainWindow", "status : ready"))
        self.stream_tab.setTabText(self.stream_tab.indexOf(self.stream), _translate("MainWindow", "Stream"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
